version: 2

defaults: &defaults
  docker:
    # Use a Docker image with Cypress already installed.
    - image: cypress/base:6
  working_directory: ~/react-axe

jobs:
  # Fetch and cache dependencies.
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cache-{{ checksum "package-lock.json" }}
      - run: npm install -g npm@latest
      # Install package dependencies.
      - run: npm install
      # Install example dependencies; they're used in tests.
      - run: npm install --prefix example
      - save_cache:
          key: v2-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - example/node_modules
            - ~/.cache

  # Run the test suite.
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cache-{{ checksum "package-lock.json" }}
      - run: npm run test

  # Release a new version.
  production_release:
    <<: *defaults
    steps:
      - checkout
      - run: npm install -g npm@latest
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - restore_cache:
          keys:
            - v2-cache-{{ checksum "package-lock.json" }}
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      # Run tests on all commits, but after installing dependencies.
      - test:
          requires:
            - dependencies
      # Run a production release on "master" commits, but only after the tests pass and dependencies are installed.
      - production_release:
          requires:
            - dependencies
            - test
          filters:
            branches:
              only: master